cart/urls.py
from . import views
from django.urls import path, include


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/(<slug_id>\d+)/', views.cart_add, name='cart_add'),
    path('remove/(<slug_id>\d+)/', views.cart_remove, name='cart_remove'),
]

config/urls.py
from urllib import request
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('cart/', include('cart.urls')),
    path('menu', include('menu.urls')),
    path('contacts', include('sendemail.urls')),
    path('', include('home.urls')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

food_back/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls', namespace='menu')),
    path('shipping', views.shipping, name='shipping'),
]

orders/urls.py
from django.urls import path
from unicodedata import name
from . import views


urlpatterns = [
    path('create/', views.order_create, name="order_create"),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>pic project</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <script src="{% static 'css/app.js' %}" defer></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container mt-3">
        {% block content %}
        {% endblock content %}
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fast Food</title>
    <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>

    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-5 col-md-10">
                    <div class="menu-bar">
                        <img src="{% static 'images/imgg1.png' %}"  alt="menu-image" width="40px" height="30px" >
                        <a href="/" class="header__logo mr-5 pt-3 pt-md-0 d-inline-block">Fast Food</a>
                        <a href="/menu" class="header__menu mr-4">Menu</a>
                        <a href="/contacts " class="header__menu mr-4">Contacts</a>
                        {% if user.is_authenticated %}
                        <a href="{% url "orders:order_create" %}" class="header__menu mr-4">
                            Checkout
                        </a>            
                        {% endif %}            
                    </div>
                </div>
            

                <div class="col-7 col-md-2 text-right mt-2">
                    {% if user.is_authenticated %}
                    <a class="header__menu header__menu--cart">
                        <img href="{% url 'cart_detail' %}" src="{% static 'images/cart-icon.svg' %}" alt="cart-image" />
                        <span>{% with total_items=cart|length %}
                            {% if cart|length > 0 %}
                                Your cart:
                                <a href="{% url "cart:cart_detail" %}">
                                    {{ total_items }} item{{ total_items|pluralize }},
                                    ${{ cart.get_total_price }}
                                </a>
                            {% else %}
                            0
                            {% endif %}
                        {% endwith %}</span>
                    </a>
                    <p><a href="{% url 'logout' %}" class="header__menu header__menu--cart">Log out</a></p>
      {% else %}
      <a href="{% url 'login' %}" class="header__menu header__menu--cart">Log In</a> <a href="{% url 'signup' %}" class="header__menu header__menu--cart">Sign Up</a>
      {% endif %}
                    <span class="header__hamburger hamburger d-md-none">&#9776;</span>
                </div>
            </div>
        </div>
    </header>

{% block content%}
    <section class="hero-banner mb-5">
        <div class="hero-banner__container col-md-4 text-center mt-5">
            <p class="hero-banner__text">Say Hello to FastFood!</p>
            <h1 class="hero-banner__title">WELCOME</h1>
            <div class="text-center pt-3 pb-3 pb-md-0">
                <a href="menu.html" class="hero-banner__btn">Open Menu</a>
            </div>
        </div>
    </section>
    



    <section class="featured-products py-4 mb-5">
        <div class="container">
            <div class="row">
                <div class="col-7 col-md-10">
                    <h3 class="featured-products__title">Food</h3>
                </div>
                <div class="col-5 col-md-2 text-right">
                    <a href="menu.html" class="featured-products__all-link">See All Food &#10140</a>
                </div>
            </div>
            <div class="row">
                <div class="col-2 border border-green mt-3"></div>
                <div class="col-10 border border-grey  mt-3"></div>
            </div>
            
            <div class="row">
                <div class="col-md-3 mt-5">
                    <a class="featured-products__card" href="hamburgertype.html">
                        <img src="images/hamburger1.png" alt="" class="featured-products__img mb-3">
                        <p class="featured-products__name"></p>
                        <span class="featured-products__btn">Hamburger</span>
                    </a>
                </div>
                
                
           
          
            </div>
            {% endblock content %}
        </div>
    </section>
    {% block content2 %}
    <section class="combo py-4 mb-5">
        <div class="container">
            <div class="row">
                <div class="col-7 col-md-10">
                    <h3 class="combo__title">Combo</h3>
                </div>
                <div class="col-5 col-md-2 text-right">
                    <a href="menu.html" class="combo__all-link">See All Food &#10140</a>
                </div>
            </div>
            <div class="row">
                <div class="col-2 border border-green mt-3"></div>
                <div class="col-10 border border-grey mt-3"></div>
            </div>
            <div class="row">
                <div class="col-md-3 mt-5">
                    <a class="combo__card" href="Combo1.html">
                        <img src="{% static 'images/pngg3.png'%}" alt="" class="combo__img mb-3" height="120">
                        <p class="combo__name">Combo1</p>
                        <span class="combo__btn">1800 ₸</span>
                    </a>
                </div>
                <div class="col-md-3 mt-5">
                    <a class="combo__card" href="Combo2.html">
                        <img src="{% static 'images/pngg4.png' %} " alt="" class="combo__img mb-3" height="120">
                        <p class="combo__name">Combo2</p>
                        <span class="combo__btn">2000 ₸</span>
                    </a>
                </div>
                <div class="col-md-3 mt-5">
                    <a class="combo__card" href="Combo3.html">
                        <img src="{% static 'images/pngg5.png' %}" alt="" class="combo__img mb-3" height="120">
                        <p class="combo__name">Combo3</p>
                        <span class="combo__btn">2500 ₸</span>
                    </a>
                </div>
                <div class="col-md-3 mt-5">
                    <a class="combo__card" href="Combo4.html">
                        <img src="{% static 'images/pngg6.png' %}" alt="" class="combo__img mb-3" height="120">
                        <p class="combo__name">Combo4</p>
                        <span class="combo__btn">3000 ₸ </span>
                    </a>
                </div>
            </div>
        </div>
    </section>
    {%endblock content2%}
    


    <section class="reveal newsletter mt-5 pt-5 pb-5">
        <div class="container newsletter__back">
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-2">
                            <span class="newsletter__video-link">
                                <img src="{% static 'images/paperplane-icon-white.svg'%}" alt="play-icon" />
                            </span>
                        </div>
                        <div class="col-md-10">
                            <h3 class="newsletter__info mt-3">Subscribe to our newsletter
                                & get <span>10% discount!</span></h3>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-9">
                            <input type="text" placeholder="Enter your email address" class="form-control newsletter__search mt-4">
                        </div>
                        <div class="col-md-3 mt-4">
                            <a href="#" class="newsletter__btn">Subscribe</a>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </section>

    <section class="food mt-5 mb-5 pb-5">
        <div class="container">
            <div class="food__title text-center mb-2">@GambIT</div>
            <h2 class="food__heading text-center mb-5 pb-4">We're on Instagram!</h2>
            <div class="food__images mb-5 pb-5">
                <a href="#">
                    <img src="{% static 'images/img1.png'%}" width="15%" alt="beautiful-toys" class="food__image" />
                </a>
                <a href="#">
                    <img src="{% static 'images/img2.png'%}" width="15%" alt="beautiful-toys" class="food__image" />
                </a>
                <a href="#">
                    <img src="{% static 'images/img3.jpg'%}" width="15%" alt="beautiful-toys" class="food__image" />
                </a>
                <a href="#">
                    <img src="{% static 'images/img4.jpg'%}" width="15%" alt="beautiful-toys" class="food__image" />
                </a>
                <a href="#">
                    <img src="{% static 'images/img5.jpg'%}" width="15%" alt="beautiful-toys" class="food__image" />
                </a>
                <a href="#">
                    <img src="{% static 'images/img6.jpg'%}" width="15%" alt="beautiful-toys" class="food__image" />
                </a>
            </div>
            <div class="text-center">
                <a href="menu.html" class="food__btn mt-5">See More Photos</a>
            </div>
        </div>
    </section>

    <section class="footer mt-5 pt-3">
        <div class="container">
            <div class="row">
                <div class="col-md-2 pt-3">
                    <a href="index.html" class="footer__logo">FastFood</a>
                </div>
                <div class="col-md-6 pt-3">
                    <a href="index.html" class="footer__link mr-4">Home</a>
                    <a href="menu.html" class="footer__link mr-4">Menu</a>
                    <a href="delivery.html" class="footer__link mr-4">Delivery</a>
                    <a href="contacts.html" class="footer__link mr-2">Contacts</a>
                </div>
                <div class="col-md-4">
                    <div class="col-md-6 pt-3">
                        <a href="#" class="footer__social-icon"><img src="{% static 'images/twitter-icon-white.svg'%}" alt="twitter-icon-white"></a>
                        <a href="#" class="footer__social-icon"><img src="{% static 'images/facebook-icon-white.svg'%}" alt="facebook-icon-white"></a>
                        <a href="#" class="footer__social-icon"><img src="{% static 'images/instagram-icon-white.svg'%}" alt="instagram-icon-white"></a>
                        <a href="#" class="footer__social-icon"><img src="{% static 'images/youtube-icon.svg'%}" alt="youtube-icon"></a>
                    </div>
                </div>
            </div>
            <p class="footer__copyrights mt-5">
                <span class="footer__copyrights-text">Copyrights 2021 &copy; GambIT</span>
            </p>
        </div>
    </section>

    
    <script src="{% static 'js/app.js' %}"></script>


</body>

</html>

    © 2022 GitHub, Inc.

    Terms
    Privacy
    Security
    Status
    Docs
    Contact GitHub
    Pricing
    API
    Training
    Blog
    About

Loading complete

templates/picture_list.html
{% extends "base.html" %}

{% block content %}

<div class="text-center">
  <div class="spinner-border" role="status" id="spinner"></div>
</div>
{% endblock content %}