cart/urls.py
from . import views
from django.urls import path, include


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/(<slug_id>\d+)/', views.cart_add, name='cart_add'),
    path('remove/(<slug_id>\d+)/', views.cart_remove, name='cart_remove'),
]

config/urls.py
from urllib import request
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('cart/', include('cart.urls')),
    path('menu', include('menu.urls')),
    path('contacts', include('sendemail.urls')),
    path('', include('home.urls')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home,name="home"),
    
]

menu/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.MenuListView.as_view(), name="menu"),
    path('<slug:slug>/', views.FoodPostListView.as_view(), name="foodPost_list"),
    path('<slug:slug>/<slug:foodPost_slug>/',
         views.FoodPostDetailView.as_view(), name="foodPost_single")
]

home/models.py
from django.db import models

# Create your models here.

menu/models.py
from distutils.command.upload import upload
from unicodedata import category
from django.db import models
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey
from ckeditor.fields import RichTextField

# Create your models here.


class Category(MPTTModel):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    image = models.ImageField(upload_to='articles/')
    parent = TreeForeignKey(
        'self',
        related_name='children',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name

    class MPTTMeta:
        order_insertion_by = ['name']


class Tag(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)

    def __str__(self):
        return self.name


class foodPost(models.Model):
    title = models.CharField(max_length=100)
    text = RichTextField()
    image = models.ImageField(upload_to='articles/')
    category = models.ForeignKey(
        Category,
        related_name='foodPost',
        on_delete=models.SET_NULL,
        null=True
    )
    cost = models.PositiveIntegerField(default=0)
    quantity = models.PositiveIntegerField(default=0)
    tags = models.ManyToManyField(Tag, related_name='foodPost')
    slug = models.SlugField(max_length=100)

    def get_absolute_url(self):
        return reverse("foodPost_single", kwargs={"slug": self.category.slug, 'foodPost_slug': self.slug})

    def __str__(self):
        return self.title

home/views.py
from django.shortcuts import render
from msilib.schema import ListView
from django.views.generic import ListView, DetailView
# Create your views here.


def home(request):
    return render(request, 'menu/home.html')

menu/views.py
from msilib.schema import ListView
from multiprocessing import context
from unicodedata import category
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, DetailView

from menu.models import Tag, foodPost, Category
from cart.forms import CartAddProductForm


# Create your views here.

class MenuListView(ListView):
    model = Category
    template_name = "menu/menu.html"


class FoodPostListView(ListView):
    model = foodPost

    def get_queryset(self):
        return foodPost.objects.filter(category__slug=self.kwargs.get('slug')).select_related('category')


class FoodPostDetailView(DetailView):
    model = foodPost
    slug_url_kwarg = 'foodPost_slug'
    context_object_name = 'post'


def home(request):
    return render(request, 'index.html')


def product_detail(request, id, slug):
    product = get_object_or_404(Tag,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'detail.html', {'slug': slug,
                                           'cart_product_form': cart_product_form})

templates/menu/foodpost_detail.html
{% extends 'index.html' %}
{% block content%}
<section class="container mb-5">
    <div class="breadcrumbs pt-3">
        <a href="index.html" class="link-grey">Home</a>
        <img src="images/arrow-right-mini-icon.svg" class="breadcrumbs-arrow">
        <div class="d-inline-block">Catalog</div>
    </div>
</section>
    <section class="menu">
        <div class="container menu__back">
            <div class="row">
                <div class="col-md-5">
                    <div class="menu__info mt-5 pt-4">
                        <h2>{{ post.title}}</h2>
                        <p>{{ post.text|safe }}</p>
                        <h4> {{ post.cost }} ₸</h4>
                        <p>Quantity</p>
                        <div class="row">
                            <div class="col">
                                <input type="number" name="number" value="1" class="menu__field pl-4">
                                <button class="menu__button">Add cart</button>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="col">
                    <img src="{{post.image.url}}" alt="big-teddy-image" class="menu__image">
                </div>
            </div>
        </div>
        </div>
    </section>

 {% endblock content%}

templates/menu/foodpost_list.html
{% extends 'index.html' %}

{% block content%}

<section class="container mb-5">
    <div class="breadcrumbs pt-3">
        <a href="index.html" class="link-grey">Home</a>
        <img src="images/arrow-right-mini-icon.svg" class="breadcrumbs-arrow">
        <div class="d-inline-block">Catalog</div>
    </div>
</section>
    <section class="featured-products py-4 mb-5">
        <div class="container">
            <div class="row">
                <div class="col-md-7">
                    <h3 class="featured-products__title">{{ foodpost_list.first.category.name }}</h3>
                </div>
                <div class="col-md-5 text-right">
                    <a href="menu.html" class="featured-products__btn featured-product__btn--active">All Food</a>
                    <a href="hamburgertype.html" class="featured-products__btn">Hamburger</a>
                    <a href="pizzatype.html" class="featured-products__btn">Pizza</a>
                    <a href="juicetype.html" class="featured-products__btn">Drinks</a>
                    <a href="donertype.html" class="featured-products__btn">Doner</a>
                </div>
            </div>
            <div class="row">
                <div class="col-2 border border-green mt-3"></div>
                <div class="col-10 border border-grey  mt-3"></div>
            </div>

            
            <div class="row">
                {% for post in foodpost_list %}
                <div class="col-md-3 mt-5">
                    <a class="featured-products__card" href="Pizza.html">
                    {% if post.title not in 'Pizza' %}
                <div class="col-md-3 mt-5">
                    <a class="featured-products__card" href="{{ post.get_absolute_url }}">
                        <img src="{{ post.image.url }}" alt="" class="featured-products__img mb-3">
                        <p class="featured-products__name">{{ post.title }}</p>
                        <span class="featured-products__btn">{{ post.cost }} ₸</span>
                    </a>
                </div>
                {% endif %}
            {% endfor %}
               
                
              
        
            </div>
        </div>
    </section>

{% endblock content %}

templates/menu/home.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fast Food</title>
    <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>

    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-5 col-md-10">
                    <div class="menu-bar">
                        <img src="{% static 'images/imgg1.png' %}"  alt="menu-image" width="40px" height="30px" >
                        <a href="/" class="header__logo mr-5 pt-3 pt-md-0 d-inline-block">Fast Food</a>
                        <a href="/menu" class="header__menu mr-4">Menu</a>
                        <a href="delivery.html" class="header__menu mr-4">Delivery</a>
                        <a href="/contacts" class="header__menu mr-4">Contacts</a>
                    </div>
                </div>
    

                <div class="col-7 col-md-2 text-right mt-2">
                    {% if user.is_authenticated %}
                    <a  class="header__menu header__menu--cart">
                        <img href="{% url 'cart_detail' %}" src="{% static 'images/cart-icon.svg' %}" alt="cart-image" />
                        <span>
                            {% with total_items=cart|length %}
        {% if cart|length > 0 %}
            Your cart:
            <a href="{% url "cart:cart_detail" %}">
                {{ total_items }} item{{ total_items|pluralize }},
                ${{ cart.get_total_price }}
            </a>
        {% else %}
            0
        {% endif %}
    {% endwith %}
                        </span>
                    </a>
                    <p><a href="{% url 'logout' %}" class="header__menu header__menu--cart">Log out</a></p>
      {% else %}
      <a href="{% url 'login' %}" class="header__menu header__menu--cart">Log In</a> <a href="{% url 'signup' %}" class="header__menu header__menu--cart">Sign Up</a>
      {% endif %}
                    <span class="header__hamburger hamburger d-md-none">&#9776;</span>
                </div>
            </div>
        </div>
    </header>
    <section class="hero-banner mb-5">
        <div class="hero-banner__container col-md-4 text-center mt-5">
            <p class="hero-banner__text">Say Hello to FastFood!</p>
            <h1 class="hero-banner__title">WELCOME</h1>
            <div class="text-center pt-3 pb-3 pb-md-0">
                <a href="/menu" class="hero-banner__btn">Open Menu</a>
            </div>
        </div>

        

    </section>
    <section class="footer mt-5 pt-3">
        <div class="container">
            <div class="row">
                <div class="col-md-2 pt-3">
                    <a href="index.html" class="footer__logo">FastFood</a>
                </div>
                <div class="col-md-6 pt-3">
                    <a href="index.html" class="footer__link mr-4">Home</a>
                    <a href="/menu" class="footer__link mr-4">Menu</a>
                    <a href="delivery.html" class="footer__link mr-4">Delivery</a>
                    <a href="/contacts" class="footer__link mr-2">Contacts</a>
                </div>
                <div class="col-md-4">
                    <div class="col-md-6 pt-3">
                        <a href="#" class="footer__social-icon"><img src="{% static 'images/twitter-icon-white.svg'%}" alt="twitter-icon-white"></a>
                        <a href="#" class="footer__social-icon"><img src="{% static 'images/facebook-icon-white.svg'%}" alt="facebook-icon-white"></a>
                        <a href="#" class="footer__social-icon"><img src="{% static 'images/instagram-icon-white.svg'%}" alt="instagram-icon-white"></a>
                        <a href="#" class="footer__social-icon"><img src="{% static 'images/youtube-icon.svg'%}" alt="youtube-icon"></a>
                    </div>
                </div>
            </div>
            <p class="footer__copyrights mt-5">
                <span class="footer__copyrights-text">Copyrights 2021 &copy; GambIT</span>
            </p>
        </div>
    </section>
    
   

      
    
    <script src="{% static 'js/app.js' %}"></script>


</body>

</html>

templates/menu/menu.html
{% extends 'index.html' %}

{% block content%}





<section class="mb-5 featured-products py-4 mb-5">
    <div class="container">
        <div class="row">
            <div class="col-7 col-md-10">
                <h3 class="featured-products__title">Food</h3>
            </div>
            <div class="col-5 col-md-2 text-right">
                <a href="menu.html" class="featured-products__all-link">See All Food &#10140</a>
            </div>
        </div>
        <div class="row">
            <div class="col-2 border border-green mt-3"></div>
            <div class="col-10 border border-grey  mt-3"></div>
        </div>
        <div class="row">
            {% for post in category_list %}
            
                <div class="col-md-3 mt-5">
                    <a class="featured-products__card" href="menu{{ post.slug }}">
                        <img src="{{ post.image.url }}" alt="" class="featured-products__img mb-3">
                        <p class="featured-products__name">{{ post.category.name }}</p>
                        <span class="featured-products__btn">{{ post.name }} </span>
                    </a>
                </div>
            {% endfor %}
        </div>
{% endblock content%}
{% comment %} {% block content2%}
<section class="combo py-4 mb-5">
    <div class="container">
        <div class="row">
            <div class="col-7 col-md-10">
                <h3 class="combo__title">Combo</h3>
            </div>
            <div class="col-5 col-md-2 text-right">
                <a href="menu.html" class="combo__all-link">See All Food &#10140</a>
            </div>
        </div>
        <div class="row">
            <div class="col-2 border border-green mt-3"></div>
            <div class="col-10 border border-grey mt-3"></div>
        </div>
        <div class="row">
            {% for post in category_list %}
            
            <div class="col-md-3 mt-5">
                <a class="featured-products__card" href="{{ post.slug }}">
                    <img src="{{ post.image.url }}" alt="" class="featured-products__img mb-3">
                    <p class="featured-products__name">{{ post.category.name }}</p> 
                    <span class="featured-products__btn">{{ post.name }} </span>
                </a>
            </div>
        {% endfor %}
            
        </div>
    </div>
</section>
{% endblock content2%} {% endcomment %}

templates/menu/shipping.html
{% load static %} 
<link rel="stylesheet" href="{% static 'flowers/shipping.css' %}"> 
<link rel="stylesheet" href="{% static 'flowers/about.css' %}"> 
 



 
<div class="row"> 
    <div class="col-lg-6"> 
        <div class="box-element" id="form-wrapper"> 
            <br><br><br><br> 
            <form id="form"> 
                <hr> 
                    <h1><p> User Information:</p></h1> 
                <hr> 
                <div id="user-info"> 
                    <div class="form-field" > 
                        <input required class="form-control" type="text" name="name" placeholder="Name.."> 
                    </div> 
                    <div class="form-field"> 
                        <input required class="form-control" type="email" name="email" placeholder="Email.."> 
                    </div> 
                </div> 
                <br><br><br><br> 
                <div id="shipping-info"> 
                    <hr> 
                    <h1><p>Shipping Information:</p></h1> 
                    <hr> 
                    <div class="form-field"> 
                        <input class="form-control" type="text" name="address" placeholder="Address.."> 
                    </div> 
                    <div class="form-field"> 
                        <input class="form-control" type="text" name="city" placeholder="City.."> 
                    </div> 
                    <div class="form-field"> 
                        <input class="form-control" type="text" name="state" placeholder="State.."> 
                    </div> 
                    <div class="form-field"> 
                        <input class="form-control" type="text" name="zipcode" placeholder="Zip code.."> 
                    </div> 
                    <div class="form-field"> 
                        <input class="form-control" type="text" name="country" placeholder="Zip code.."> 
                    </div> 
                </div> 
 
                <hr> 
                <input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue"> 
            </form> 
        </div> 
 
        <br> 
        <div class="box-element hidden" id="payment-info"> 
            <small>Paypal Options</small> 
            <!--<button id="make-payment">Make payment</button>--> 
            <div id="paypal-button-container"></div> 
        </div> 
         
    </div>